---
name: "auto-release"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: gh release create v1.0.4 --notes "Mosquito Alert Sampling Effort Data."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
