---
name: "auto-release"

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
              Open access data on Mosquito Alert participation and sampling effort.

              This dataset contains data on participation and sampling effort in the [Mosquito Alert](http://www.mosquitoalert.com/) citizen science system. It can be used for a variety of purposes, including (a) to adjust estimates of mosquito population densities and human-mosquito encounters based on sampling effort, and (b) to better understand the dynamics of citizen scientists' participation. The data is organized spatially by grids of "sampling cells," drawn at intervals of 0.05 degree and 0.025 degree latitude and longitude, and it is based on optional anonymous background tracks from the Mosquito Alert app. The dataset includes raw track counts aggregated in sampling cells, along with estimates of sampling effort based on a model of participants' propensity to send any report as a function of the time elapsed since they first began participating.

              The repository is hosted on both [Zenodo](https://doi.org/10.5281/zenodo.5802476) and [GitHub](https://github.com/Mosquito-Alert/sampling_effort_data) and contains the following files:

              * `sampling_effort_daily_cellres_025.csv.gz` - Daily participation and sampling effort in 0.025 degree sampling cells.
              * `sampling_effort_daily_cellres_025_metadata.json` - Metadata for the 0.025 degree sampling cell data. 
              * `sampling_effort_daily_cellres_05.csv.gz` - daily participation and sampling effort in 0.05 degree sampling cells.
              * `sampling_effort_daily_cellres_05_metadata.json` - Metadata for the 0.05 degree sampling cell data. 
              * `CITATION.cff` - Shows how to cite this dataset.
              * `LICENSE` - License for this dataset.
              * `.gitignore` - Specifies which files are excluded from the git repository.
              * `README.md` - This file.
              * `.github/workflows/auto-release.yml` - Script used for automating releases from GitHub.
          draft: false
          prerelease: false
